# Sector mapping for all 206 NSE F&O stocks
# Sectors: FINANCIALS, IT, CONSUMER, AUTO, PHARMA, ENERGY, METALS, INFRA, REALTY, TELECOM, CHEMICALS, CAPITAL_GOODS, MEDIA, OTHERS

SECTOR_MAP = {
    # FINANCIALS
    "HDFCBANK":     "FINANCIALS",
    "ICICIBANK":    "FINANCIALS",
    "KOTAKBANK":    "FINANCIALS",
    "AXISBANK":     "FINANCIALS",
    "SBIN":         "FINANCIALS",
    "BANKBARODA":   "FINANCIALS",
    "BANDHANBNK":   "FINANCIALS",
    "FEDERALBNK":   "FINANCIALS",
    "IDFCFIRSTB":   "FINANCIALS",
    "INDUSINDBK":   "FINANCIALS",
    "PNB":          "FINANCIALS",
    "RBLBANK":      "FINANCIALS",
    "YESBANK":      "FINANCIALS",
    "AUBANK":       "FINANCIALS",
    "INDIANB":      "FINANCIALS",
    "UNIONBANK":    "FINANCIALS",
    "CANBK":        "FINANCIALS",
    "BAJFINANCE":   "FINANCIALS",
    "BAJAJFINSV":   "FINANCIALS",
    "CHOLAFIN":     "FINANCIALS",
    "MFSL":         "FINANCIALS",
    "PNBHOUSING":   "FINANCIALS",
    "ABCAPITAL":    "FINANCIALS",
    "SHRIRAMFIN":   "FINANCIALS",
    "JIOFIN":       "FINANCIALS",
    "LTF":          "FINANCIALS",
    "SAMMAANCAP":   "FINANCIALS",
    "HDFCLIFE":     "FINANCIALS",
    "SBILIFE":      "FINANCIALS",
    "ICICIGI":      "FINANCIALS",
    "ICICIPRULI":   "FINANCIALS",
    "LICI":         "FINANCIALS",
    "POLICYBZR":    "FINANCIALS",
    "NUVAMA":       "FINANCIALS",
    "360ONE":       "FINANCIALS",
    "ANGELONE":     "FINANCIALS",
    "KFINTECH":     "FINANCIALS",
    "CAMS":         "FINANCIALS",
    "BSE":          "FINANCIALS",
    "MCX":          "FINANCIALS",
    "RECLTD":       "FINANCIALS",
    "PFC":          "FINANCIALS",
    "IRFC":         "FINANCIALS",
    "HUDCO":        "FINANCIALS",

    # IT
    "TCS":          "IT",
    "INFY":         "IT",
    "WIPRO":        "IT",
    "HCLTECH":      "IT",
    "TECHM":        "IT",
    "LTIM":         "IT",
    "MPHASIS":      "IT",
    "COFORGE":      "IT",
    "PERSISTENT":   "IT",
    "TATAELXSI":    "IT",
    "TATATECH":     "IT",
    "KAYNES":       "IT",
    "KPITTECH":     "IT",

    # CONSUMER
    "HINDUNILVR":   "CONSUMER",
    "ITC":          "CONSUMER",
    "NESTLEIND":    "CONSUMER",
    "BRITANNIA":    "CONSUMER",
    "DABUR":        "CONSUMER",
    "MARICO":       "CONSUMER",
    "GODREJCP":     "CONSUMER",
    "COLPAL":       "CONSUMER",
    "VBL":          "CONSUMER",
    "TATACONSUM":   "CONSUMER",
    "PATANJALI":    "CONSUMER",
    "JUBLFOOD":     "CONSUMER",
    "DMART":        "CONSUMER",
    "NYKAA":        "CONSUMER",
    "KALYANKJIL":   "CONSUMER",
    "TITAN":        "CONSUMER",
    "PAGEIND":      "CONSUMER",
    "MANYAVAR":     "CONSUMER",
    "ABFRL":        "CONSUMER",
    "TRENT":        "CONSUMER",
    "SWIGGY":       "CONSUMER",
    "PAYTM":        "CONSUMER",

    # AUTO
    "MARUTI":       "AUTO",
    "TATAMOTORS":   "AUTO",
    "M&M":          "AUTO",
    "BAJAJ-AUTO":   "AUTO",
    "HEROMOTOCO":   "AUTO",
    "EICHERMOT":    "AUTO",
    "ASHOKLEY":     "AUTO",
    "TVSMOTOR":     "AUTO",
    "MOTHERSON":    "AUTO",
    "BOSCHLTD":     "AUTO",
    "BALKRISIND":   "AUTO",
    "EXIDEIND":     "AUTO",
    "SONACOMS":     "AUTO",
    "UNOMINDA":     "AUTO",
    "TIINDIA":      "AUTO",
    "TMPV":         "AUTO",

    # PHARMA
    "SUNPHARMA":    "PHARMA",
    "DRREDDY":      "PHARMA",
    "CIPLA":        "PHARMA",
    "DIVISLAB":     "PHARMA",
    "BIOCON":       "PHARMA",
    "AUROPHARMA":   "PHARMA",
    "LUPIN":        "PHARMA",
    "ALKEM":        "PHARMA",
    "TORNTPHARM":   "PHARMA",
    "GLENMARK":     "PHARMA",
    "IPCALAB":      "PHARMA",
    "ABBOTINDIA":   "PHARMA",
    "PPLPHARMA":    "PHARMA",
    "MANKIND":      "PHARMA",
    "MAXHEALTH":    "PHARMA",
    "FORTIS":       "PHARMA",
    "APOLLOHOSP":   "PHARMA",

    # ENERGY
    "RELIANCE":     "ENERGY",
    "ONGC":         "ENERGY",
    "BPCL":         "ENERGY",
    "IOC":          "ENERGY",
    "OIL":          "ENERGY",
    "GAIL":         "ENERGY",
    "IGL":          "ENERGY",
    "MGL":          "ENERGY",
    "HINDPETRO":    "ENERGY",
    "ADANIENT":     "ENERGY",
    "ADANIENSOL":   "ENERGY",
    "TATAPOWER":    "ENERGY",
    "NTPC":         "ENERGY",
    "POWERGRID":    "ENERGY",
    "NHPC":         "ENERGY",
    "TORNTPOWER":   "ENERGY",
    "JSWENERGY":    "ENERGY",
    "SUZLON":       "ENERGY",
    "WAAREEENER":   "ENERGY",
    "INOXWIND":     "ENERGY",
    "IREDA":        "ENERGY",
    "SOLARINDS":    "ENERGY",
    "PREMIERENE":   "ENERGY",
    "POWERINDIA":   "ENERGY",

    # METALS
    "TATASTEEL":    "METALS",
    "JSWSTEEL":     "METALS",
    "HINDALCO":     "METALS",
    "VEDL":         "METALS",
    "SAIL":         "METALS",
    "NATIONALUM":   "METALS",
    "HINDZINC":     "METALS",
    "COALINDIA":    "METALS",
    "NMDC":         "METALS",
    "APLAPOLLO":    "METALS",
    "KEI":          "METALS",
    "SUPREMEIND":   "METALS",

    # INFRA / CONSTRUCTION
    "LARSEN":       "INFRA",
    "ULTRACEMCO":   "INFRA",
    "SHREECEM":     "INFRA",
    "AMBUJACEM":    "INFRA",
    "ACC":          "INFRA",
    "RVNL":         "INFRA",
    "NBCC":         "INFRA",
    "MAZDOCK":      "INFRA",
    "BDL":          "INFRA",
    "GMRAIRPORT":   "INFRA",
    "DELHIVERY":    "INFRA",
    "CGPOWER":      "INFRA",
    "ABB":          "INFRA",
    "SIEMENS":      "INFRA",
    "PGEL":         "INFRA",

    # REALTY
    "DLF":          "REALTY",
    "OBEROIRLTY":   "REALTY",
    "GODREJPROP":   "REALTY",
    "PRESTIGE":     "REALTY",
    "PHOENIXLTD":   "REALTY",
    "LODHA":        "REALTY",

    # TELECOM
    "BHARTIARTL":   "TELECOM",
    "IDEA":         "TELECOM",

    # CHEMICALS
    "PIDILITIND":   "CHEMICALS",
    "ASIANPAINT":   "CHEMICALS",
    "BERGEPAINT":   "CHEMICALS",
    "DEEPAKNTR":    "CHEMICALS",
    "AARTIIND":     "CHEMICALS",
    "NAVINFLUOR":   "CHEMICALS",

    # CAPITAL GOODS
    "HAVELLS":      "CAPITAL_GOODS",
    "VOLTAS":       "CAPITAL_GOODS",
    "BLUESTARCO":   "CAPITAL_GOODS",
    "AMBER":        "CAPITAL_GOODS",
    "WHIRLPOOL":    "CAPITAL_GOODS",
    "CUMMINSIND":   "CAPITAL_GOODS",
    "BHEL":         "CAPITAL_GOODS",

    # OTHERS
    "ZOMATO":       "OTHERS",
    "NAUKRI":       "OTHERS",
    "INDIAMART":    "OTHERS",
    "IEX":          "OTHERS",
    "CONCOR":       "OTHERS",
    "IRCTC":        "OTHERS",
    "LTM":          "OTHERS",
    "BAJAJHLDNG":   "OTHERS",
    "HDFCAMC":      "OTHERS",
    "MCDOWELL-N":   "OTHERS",

    # INFRA additions
    "ADANIPORTS":   "INFRA",
    "HAL":          "INFRA",
    "BEL":          "INFRA",
    "LT":           "INFRA",
    "BHARATFORG":   "INFRA",
    "POLYCAB":      "INFRA",
    "CROMPTON":     "CAPITAL_GOODS",
    "DIXON":        "CAPITAL_GOODS",
    "ASTRAL":       "CAPITAL_GOODS",

    # ENERGY additions
    "ADANIGREEN":   "ENERGY",
    "PETRONET":     "ENERGY",
    "INDUSTOWER":   "TELECOM",

    # METALS additions
    "JINDALSTEL":   "METALS",
    "GRASIM":       "METALS",
    "DALBHARAT":    "INFRA",

    # FINANCIALS additions
    "BANKINDIA":    "FINANCIALS",
    "SBICARD":      "FINANCIALS",
    "LICHSGFIN":    "FINANCIALS",
    "MANAPPURAM":   "FINANCIALS",
    "MUTHOOTFIN":   "FINANCIALS",
    "CDSL":         "FINANCIALS",

    # PHARMA additions
    "LAURUSLABS":   "PHARMA",
    "SYNGENE":      "PHARMA",
    "ZYDUSLIFE":    "PHARMA",
    "PIIND":        "CHEMICALS",
    "SRF":          "CHEMICALS",
    "UPL":          "CHEMICALS",

    # IT additions
    "OFSS":         "IT",

    # CONSUMER additions
    "INDHOTEL":     "CONSUMER",
    "UNITDSPR":     "CONSUMER",
    "ETERNAL":      "CONSUMER",

    # AUTO additions
    "INDIGO":       "AUTO",
}
